### ISSUE TITLE
non-GPL license

### ISSUE THREAD

**Issue by themighty1** [arnaucube/poseidon-rs#3]
HI, is there any chance you could change the license of this repo to MIT/Apache 2.0
Or, alternatively, could you license it to out project https://github.com/tlsnotary with a MIT/Apache 2.0 license?
Thanks., @arnaucube

**Comment by arnaucube** [comment]
Hi, sorry for the delay in the answer.
While I like the idea of using GPLv3 to ensure that the derived usages of the code will remain also open source, I'm open to moving the license to Apache2.

**Comment by arnaucube** [comment]
Closing as it was migrated to Apache2 https://github.com/arnaucube/poseidon-rs/commit/233027d6075a637c29ad84a8a44f5653b81f0410
